In [25]:
import pandas as pd
import numpy as np

In [26]:
df2=pd.read_csv('Titanic-Dataset.csv')
df2.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [27]:
Y=df2['Survived']


In [28]:
X= df2.drop(["PassengerId", "Name", "Ticket","Survived","Cabin"], axis=1)
X.head()


Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

#Dealing with null values

---



In [29]:
X.isnull().mean()*100

Pclass       0.000000
Sex          0.000000
Age         19.865320
SibSp        0.000000
Parch        0.000000
Fare         0.000000
Embarked     0.224467
dtype: float64

#Forward/Backward Fill method




In [30]:
X['Age'] = X['Age'].ffill()   # forward fill



#simpleimputer method

In [7]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='median')

X[['Age']] = si.fit_transform(X[['Age']])
X


Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female  19.0      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

#missing values for categorical columns

In [31]:
from sklearn.impute import SimpleImputer
cat_imputer = SimpleImputer(strategy='most_frequent')
X[['Embarked']] = cat_imputer.fit_transform(X[['Embarked']])
X

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female  19.0      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

#converting categorical values to numerical values

In [32]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
X[['Embarked','Sex']] = encoder.fit_transform(X[['Embarked','Sex']])
X

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         3  1.0  22.0      1      0   7.2500       2.0
1         1  0.0  38.0      1      0  71.2833       0.0
2         3  0.0  26.0      0      0   7.9250       2.0
3         1  0.0  35.0      1      0  53.1000       2.0
4         3  1.0  35.0      0      0   8.0500       2.0
..      ...  ...   ...    ...    ...      ...       ...
886       2  1.0  27.0      0      0  13.0000       2.0
887       1  0.0  19.0      0      0  30.0000       2.0
888       3  0.0  19.0      1      2  23.4500       2.0
889       1  1.0  26.0      0      0  30.0000       0.0
890       3  1.0  32.0      0      0   7.7500       1.0

[891 rows x 7 columns]

In [33]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [34]:
ct=ColumnTransformer(transformers=[
        ('cat', OneHotEncoder(), ['Embarked', 'Sex'])  # list of columns to encode
    ],
    remainder='passthrough')

X = ct.fit_transform(X)
print(X[0])

[ 0.    0.    1.    0.    1.    3.   22.    1.    0.    7.25]


#Scaling

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
ss=StandardScaler()
X=ss.fit_transform(X)
X

array([[-0.48204268, -0.30756234,  0.61583843, ...,  0.43279337,
        -0.47367361, -0.50244517],
       [ 2.0745051 , -0.30756234, -1.62380254, ...,  0.43279337,
        -0.47367361,  0.78684529],
       [-0.48204268, -0.30756234,  0.61583843, ..., -0.4745452 ,
        -0.47367361, -0.48885426],
       ...,
       [-0.48204268, -0.30756234,  0.61583843, ...,  0.43279337,
         2.00893337, -0.17626324],
       [ 2.0745051 , -0.30756234, -1.62380254, ..., -0.4745452 ,
        -0.47367361, -0.04438104],
       [-0.48204268,  3.25137334, -1.62380254, ..., -0.4745452 ,
        -0.47367361, -0.49237783]])

In [39]:
from sklearn.model_selection import train_test_split

# split into 80% train and 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X,Y, test_size=0.2, random_state=42, stratify=Y
)


In [40]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Create and train the model
dt_model = DecisionTreeClassifier(
    criterion='gini',   # or 'entropy'
    max_depth=5,        # controls tree depth (to avoid overfitting)
    random_state=42
)

dt_model.fit(X_train, y_train)

# Predictions
y_pred_dt = dt_model.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))
print("\nClassification Report:\n", classification_report(y_test, y_pred_dt))


Accuracy: 0.776536312849162

Confusion Matrix:
 [[98 12]
 [28 41]]

Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.89      0.83       110
           1       0.77      0.59      0.67        69

    accuracy                           0.78       179
   macro avg       0.78      0.74      0.75       179
weighted avg       0.78      0.78      0.77       179

